export const POPULAR_MOVIE = [
  {
    adult: false,
    backdrop_path: '/path_to_backdrop1.jpg',
    genre_ids: [28, 12],
    id: 101,
    original_language: 'en',
    original_title: 'Mock Movie One',
    overview: 'This is a mock overview for movie one.',
    popularity: 123.45,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2025-01-15',
    title: 'Mock Movie One',
    video: false,
    vote_average: 7.8,
    vote_count: 1500,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop2.jpg',
    genre_ids: [16, 35],
    id: 102,
    original_language: 'ja',
    original_title: 'Mock Movie Two',
    overview: 'Second mock movie with more fun.',
    popularity: 95.12,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2025-03-12',
    title: 'Mock Movie Two',
    video: false,
    vote_average: 6.9,
    vote_count: 950,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
];

export const FOOTER_NAVS = [
  {
    title: 'Home',
    items: ['Categories', 'Devices', 'Pricing', 'FAQ'],
  },
  {
    title: 'Movies',
    items: ['Genres', 'Trending', 'New Release', 'Popular'],
  },
  {
    title: 'Shows',
    items: ['Genres', 'Trending', 'New Release', 'Popular'],
  },
  {
    title: 'Support',
    items: ['Contact Us'],
  },
  {
    title: 'Subscription',
    items: ['Plans', 'Features'],
  },
  {
    title: 'Connect With Us',
    icons: [
      { name: 'facebook', iconClass: 'assets/icons/social-fb.svg' },
      { name: 'twitter', iconClass: 'assets/icons/social-X.svg' },
      { name: 'linkedin', iconClass: 'assets/icons/social-linkedin.svg' },
    ],
  },
];

export const HOME_SECTIONS = [
  {
    key: 'trending',
    title: 'Trending',
    btnGroup: [
      { label: 'Today', value: 'today' },
      { label: 'This Week', value: 'week' },
    ],
    data: [], 
  },
  {
    key: 'trailer',
    title: 'Lastest Trailer',
    btnGroup: [
      { label: 'Today', value: 'today' },
      { label: 'This Week', value: 'week' },
    ],
    data: [],
  },
  {
    key: 'popular',
    title: 'Popular',
    btnGroup: [
      { label: 'Today', value: 'today' },
      { label: 'This Week', value: 'week' },
    ],
    data: [],
  },
];
