import { SectionModel } from 'src/app/features/film/models/section';
import { TrendingFilm } from './../../../features/film/models/trendingMovie';
import { MovieDetail } from 'src/app/features/film/models/movieDetail';

export const POPULAR_MOVIE = [
  {
    adult: false,
    backdrop_path: '/path_to_backdrop1.jpg',
    genre_ids: [28, 12],
    id: 101,
    original_language: 'en',
    original_title: 'Mock Movie One',
    overview: 'This is a mock overview for movie one.',
    popularity: 123.45,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2025-01-15',
    title: 'Mock Movie One',
    video: false,
    vote_average: 7.8,
    vote_count: 1500,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop2.jpg',
    genre_ids: [16, 35],
    id: 102,
    original_language: 'ja',
    original_title: 'Mock Movie Two',
    overview: 'Second mock movie with more fun.',
    popularity: 95.12,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2025-03-12',
    title: 'Mock Movie Two',
    video: false,
    vote_average: 6.9,
    vote_count: 950,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
  {
    adult: false,
    backdrop_path: '/path_to_backdrop3.jpg',
    genre_ids: [18, 80],
    id: 103,
    original_language: 'fr',
    original_title: 'Mock Movie Three',
    overview: 'A dramatic mock story with suspense.',
    popularity: 77.89,
    poster_path: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    release_date: '2024-11-01',
    title: 'Mock Movie Three',
    video: false,
    vote_average: 8.2,
    vote_count: 2100,
  },
];

export const FOOTER_NAVS = [
  {
    title: 'Home',
    items: ['Categories', 'Devices', 'Pricing', 'FAQ'],
  },
  {
    title: 'Movies',
    items: ['Genres', 'Trending', 'New Release', 'Popular'],
  },
  {
    title: 'Shows',
    items: ['Genres', 'Trending', 'New Release', 'Popular'],
  },
  {
    title: 'Support',
    items: ['Contact Us'],
  },
  {
    title: 'Subscription',
    items: ['Plans', 'Features'],
  },
  {
    title: 'Connect With Us',
    icons: [
      { name: 'facebook', iconClass: 'assets/icons/social-fb.svg' },
      { name: 'twitter', iconClass: 'assets/icons/social-X.svg' },
      { name: 'linkedin', iconClass: 'assets/icons/social-linkedin.svg' },
    ],
  },
];

export const HOME_SECTIONS: SectionModel[] = [
  {
    key: 'trending',
    title: 'Trending',
    btnGroup: [
      { label: 'Today', value: 'day' },
      { label: 'This Week', value: 'week' },
    ],
    data: [],
    dataType: 'default',

    subNav: '',
  },
  {
    key: 'trailer',
    title: 'Lastest Trailer',
    btnGroup: [
      { label: 'Popular', value: 'popular' },
      { label: 'Intheater', value: 'intheater' },
    ],
    data: [],
    dataType: 'trailer',

    subNav: '',
  },
  {
    key: 'popular',
    title: `What's popular`,
    btnGroup: [
      { label: 'Today', value: 'today' },
      { label: 'This Week', value: 'week' },
    ],
    data: [],
    dataType: 'default',

    subNav: '',
  },
  // {
  //   key: 'leaderboard',
  //   title: `Leaderboard`,
  //   btnGroup: [
  //     { label: 'Today', value: 'today' },
  //     { label: 'This Week', value: 'week' },
  //   ],
  //   data: [],
  //   isMovieHorizontal: false,
  //
  // },
];
export const DETAIL_SECTIONS: SectionModel[] = [
  {
    key: 'cast',
    title: 'Series Cast',
    btnGroup: [],
    data: [],
    dataType: 'cast',

    subNav: 'Full Cast & Crew',
  },
  {
    key: 'season',
    title: 'Current Season',
    btnGroup: [],
    data: [],
    dataType: 'default',

    subNav: 'View all season',
  },
  {
    key: 'social',
    title: `Social`,
    btnGroup: [
      { label: 'Review', value: 'review' },
      { label: 'Discussion', value: 'discussion' },
    ],
    data: [],
    dataType: 'social',

    subNav: 'View all review',
  },
  {
    key: 'media',
    title: `Media`,
    btnGroup: [
      { label: 'Most Popular', value: 'popular' },
      { label: 'Video', value: 'video' },
      { label: 'Backdrop', value: 'backdrop' },
      { label: 'Poster', value: 'poster' },
    ],
    data: [],
    dataType: 'media',

    subNav: '',
  },
  {
    key: 'recommend',
    title: `Recommendations`,
    btnGroup: [],
    data: [],
    dataType: 'recommendation',

    subNav: '',
  },
];

export const leaderboardMockData = [
  {
    id: 1,
    username: 'Shei',
    avatarUrl: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    allTimeEdits: 1901701,
    weeklyEdits: 11720,
    initials: 'S',
    color: '#f0c419',
  },
  {
    id: 2,
    username: 'bayramova',
    allTimeEdits: 300449,
    weeklyEdits: 8345,
    initials: 'B',
    color: '#888888',
  },
  {
    id: 3,
    username: 'zoulnix',
    avatarUrl: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    allTimeEdits: 103625,
    weeklyEdits: 7167,
    initials: 'Z',
    color: '#ccc',
  },
  {
    id: 4,
    username: 'vaugouin',
    allTimeEdits: 463727,
    avatarUrl: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    weeklyEdits: 6309,
    initials: 'V',
    color: '#c1bcbc',
  },
  {
    id: 5,
    username: 'hung0733',
    allTimeEdits: 29224,
    weeklyEdits: 5491,
    initials: 'H',
    color: '#e6007a',
  },
  {
    id: 6,
    username: 'enterpr1se',
    avatarUrl: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    allTimeEdits: 529301,
    weeklyEdits: 10759,
    initials: 'E',
    color: '#111',
  },
  {
    id: 7,
    username: 'janar',
    avatarUrl: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    allTimeEdits: 418550,
    weeklyEdits: 7758,
    initials: 'J',
    color: '#ddc34a',
  },
  {
    id: 8,
    username: 'raze464',
    avatarUrl: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    allTimeEdits: 1087743,
    weeklyEdits: 6431,
    initials: 'R',
    color: '#c33',
  },
  {
    id: 9,
    username: 'HeelerCattle86',
    avatarUrl: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    allTimeEdits: 193747,
    weeklyEdits: 5624,
    initials: 'H',
    color: '#d37846',
  },
  {
    id: 10,
    username: 'CXC6000',
    allTimeEdits: 306265,
    avatarUrl: 'assets/images/80b5d5c9724ee31a57bb49f721b164f6bc4f707f.png',
    weeklyEdits: 4839,
    initials: 'C',
    color: '#c11244',
  },
];
